//    Tina POS is a point of sales application designed for touch screens.
//    Copyright (C) 2005 Adrian Romero Corchado.
//    http://sourceforge.net/projects/tinapos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package net.adrianromero.tpv.admin;

import javax.swing.JComponent;
import net.adrianromero.basic.BasicException;
import net.adrianromero.data.user.EditorItem;
import net.adrianromero.data.user.EditorRecordBasic;
import net.adrianromero.data.user.EditorView;
import net.adrianromero.format.Formats;
import net.adrianromero.tpv.forms.AppLocal;

public class RolesView extends javax.swing.JPanel implements EditorView {
    
    /** Creates new form RolesEditor */
    public RolesView() {
        initComponents();
    }
    public void init(EditorRecordBasic editor) {
        editor.addTextComponent(m_jName, EditorItem.EDITABLE_PK);
        editor.addTextComponent(m_jText, EditorItem.EDITABLE_NORMAL);
    }
    public void writeValue(Object value) {
        Object[] role = (Object[]) value;
        m_jName.setText(Formats.STRING.formatValue(role[0]));
        try {
            m_jText.setText(role[1] == null 
                    ? null
                    : new String((byte[]) role[1], "UTF-8"));
        } catch (java.io.UnsupportedEncodingException eu) {
            m_jText.setText(null);
        }
        m_jText.setCaretPosition(0);
    }
    public Object readValue() throws BasicException {
        Object[] role = new Object[2];
        role[0] = m_jName.getText();
        try {
            role[1] = m_jText.getText().getBytes("UTF-8");
        } catch (java.io.UnsupportedEncodingException eu) {
            role[1] = null;
        }
        return role;
    }
    public JComponent getComponent() {
        return this;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_jText = new javax.swing.JTextArea();

        setLayout(null);

        jLabel2.setText(AppLocal.getIntString("label.peoplename"));
        add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 14);

        add(m_jName);
        m_jName.setBounds(100, 20, 260, 19);

        m_jText.setFont(new java.awt.Font("DialogInput", 0, 13));
        jScrollPane1.setViewportView(m_jText);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 50, 340, 350);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m_jName;
    private javax.swing.JTextArea m_jText;
    // End of variables declaration//GEN-END:variables
    
}
