//    Tina POS is a point of sales application designed for touch screens.
//    Copyright (C) 2005 Adrian Romero Corchado.
//    http://sourceforge.net/projects/tinapos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package net.adrianromero.tpv.panelsales;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import net.adrianromero.tpv.forms.AppLocal;
import net.adrianromero.tpv.ticket.TicketInfo;

public class JTicketsBagMultiList extends javax.swing.JDialog {
    
    private int m_iDialogTicket;
    
    /** Creates new form JTicketsBagMultiList */
    public JTicketsBagMultiList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }
    /** Creates new form JTicketsBagMultiList */
    public JTicketsBagMultiList(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
    }  
    
    public int showTicketsList(java.util.List<TicketInfo> atickets) {
        
        for (int i = 0; i < atickets.size(); i++) {
            m_jtickets.add(new JButtonTicket(atickets.get(i), i));                
        }  
     
        m_iDialogTicket = -1;
        setVisible(true);
        return m_iDialogTicket;
    }  
        
    public static JTicketsBagMultiList newJDialog(JTicketsBagMulti ticketsbagmulti) {
        
        Window window = getWindow(ticketsbagmulti);
        JTicketsBagMultiList mydialog;
        if (window instanceof Frame) { 
            mydialog = new JTicketsBagMultiList((Frame) window, true);
        } else {
            mydialog = new JTicketsBagMultiList((Dialog) window, true);
        } 
        
        mydialog.initComponents();
        
        mydialog.jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(35, 35));
        
        return mydialog;
    }
    
    private static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window) parent;
        } else {
            return getWindow(parent.getParent());
        }
    }  

    private class JButtonTicket extends JButton {
        
        private int  m_iTicket;
        
        public JButtonTicket(TicketInfo ticket, int i){
            
            super();
            
            m_iTicket = i;
            setFocusPainted(false);
            setFocusable(false);
            setRequestFocusEnabled(false);
            setMargin(new Insets(8, 14, 8, 14));
            //setFont(new java.awt.Font ("Dialog", 1, 24));    
            //setBackground(new java.awt.Color (220, 220, 220));
            addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    
                    // Selecciono el ticket
                    m_iDialogTicket = m_iTicket;
   
                    // y oculto la ventana
                    JTicketsBagMultiList.this.setVisible(false);
                }
            });
            
            setText(String.valueOf(ticket.getId()));
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        m_jtickets = new javax.swing.JPanel();

        setTitle(AppLocal.getIntString("caption.tickets"));
        setResizable(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setLayout(new java.awt.BorderLayout());

        m_jtickets.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

        m_jtickets.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.add(m_jtickets, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-162)/2, (screenSize.height-248)/2, 162, 248);
    }// </editor-fold>//GEN-END:initComponents
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel m_jtickets;
    // End of variables declaration//GEN-END:variables
    
}
