//    Tina POS is a point of sales application designed for touch screens.
//    Copyright (C) 2005 Adrian Romero Corchado.
//    http://sourceforge.net/projects/tinapos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package net.adrianromero.barcode;

import java.awt.*;
/**
 *
 * @author  Adrian
 */
public class ABarCodePanel extends javax.swing.JPanel {
    
    private ABarCode bc;
    /** Creates new form ABarCodePanel */
    public ABarCodePanel(ABarCode bc) {
        this.bc = bc;
        initComponents();
    }
    
    protected void paintComponent(java.awt.Graphics g) {
        Insets in = this.getInsets();
        bc.paint(g
                , (getWidth() + in.left - in.right - bc.getWidth()) / 2
                , (getHeight() + in.top - in.bottom - bc.getHeight()) / 2
        );
    }
    
    public Dimension getPreferredSize() {
        Insets in = getInsets();
        return new Dimension(bc.getWidth() + in.left + in.right, bc.getHeight() + in.top + in.bottom);
    }
    public Dimension getMinimumSize() {
        Insets in = getInsets();
        return new Dimension(bc.getWidth() + in.left + in.right, bc.getHeight() + in.top + in.bottom);
    }
    public Dimension getMaximumSize() {
        Insets in = getInsets();
        return new Dimension(bc.getWidth() + in.left + in.right, bc.getHeight() + in.top + in.bottom);
   }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.BorderLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
