//    Tina POS is a point of sales application designed for touch screens.
//    Copyright (C) 2005 Adrian Romero Corchado.
//    http://sourceforge.net/projects/tinapos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

package net.adrianromero.tpv.reports;

import net.adrianromero.basic.BasicException;
import net.adrianromero.data.loader.QBFCompareEnum;
import net.adrianromero.data.user.EditorCreator;
import net.adrianromero.tpv.forms.AppLocal;
import net.adrianromero.tpv.panels.ComboBoxModelKey;

public class JParamsReason extends javax.swing.JPanel implements EditorCreator {
    
    private ComboBoxModelKey m_ReasonModel;
    
    /** Creates new form JParamsReason */
    public JParamsReason() {
        initComponents();
        
        m_ReasonModel = new ComboBoxModelKey();
        m_ReasonModel.add(null, "");       
        m_ReasonModel.add(new Integer(+1), AppLocal.getIntString("stock.in.purchase"));
        m_ReasonModel.add(new Integer(+2), AppLocal.getIntString("stock.in.refund"));
        m_ReasonModel.add(new Integer(+4), AppLocal.getIntString("stock.in.movement"));
        m_ReasonModel.add(new Integer(-1), AppLocal.getIntString("stock.out.sale"));
        m_ReasonModel.add(new Integer(-2), AppLocal.getIntString("stock.out.refund"));
        m_ReasonModel.add(new Integer(-3), AppLocal.getIntString("stock.out.break"));        
        m_ReasonModel.add(new Integer(-4), AppLocal.getIntString("stock.out.movement"));               
        
        m_jreason.setModel(m_ReasonModel);        
    }
    
    public Object createValue() throws BasicException {
        
        return new Object[] {
            m_ReasonModel.getSelectedKey() == null ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_EQUALS, m_ReasonModel.getSelectedKey()
        };
    }       
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        m_jreason = new javax.swing.JComboBox();

        setLayout(null);

        setBorder(javax.swing.BorderFactory.createTitledBorder(AppLocal.getIntString("label.byreason")));
        setPreferredSize(new java.awt.Dimension(400, 60));
        jLabel2.setText(AppLocal.getIntString("label.stockreason"));
        add(jLabel2);
        jLabel2.setBounds(20, 20, 100, 14);

        add(m_jreason);
        m_jreason.setBounds(150, 20, 220, 20);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox m_jreason;
    // End of variables declaration//GEN-END:variables
    
}
