//    Tina POS is a point of sales application designed for touch screens.
//    Copyright (C) 2005 Adrian Romero Corchado.
//    http://sourceforge.net/projects/tinapos
//
//    This program is free software; you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation; either version 2 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program; if not, write to the Free Software
//    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


package net.adrianromero.tpv.forms;

import javax.swing.JComponent;
import javax.swing.JPanel;

public class JPanelNull extends JPanel implements JPanelView {

    /** Creates new form JPanelNull */
    public JPanelNull(AppView oApp) {
       
        initComponents ();
    }

    public JComponent getComponent() {
        return this;
    }
    public String getTitle() {
        return null;
    }
    public void activate() {
    }
    public boolean deactivate() {
        return true;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        m_jLabelError = new javax.swing.JLabel();

        setLayout(null);

        m_jLabelError.setFont(new java.awt.Font("Dialog", 1, 14));
        m_jLabelError.setText(AppLocal.getIntString("Label.LoadError"));
        add(m_jLabelError);
        m_jLabelError.setBounds(30, 30, 490, 20);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel m_jLabelError;
    // End of variables declaration//GEN-END:variables

}
